version: '3.9'

services:
  tmdt-db:
    image: postgres:16
    container_name: tmdt-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tmdt
    ports:
      - "5434:5432"
    volumes:
      - tmdt_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tmdt"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  tmdt_postgres_data: 