package fit.nlu.tmdt.modules.voucher.entity;

import fit.nlu.tmdt.common.base.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Voucher Entity
 * Lưu thông tin mã giảm giá
 */
@Entity
@Table(name = "vouchers", indexes = {
        @Index(name = "idx_voucher_code", columnList = "code", unique = true),
        @Index(name = "idx_voucher_active", columnList = "is_active"),
        @Index(name = "idx_voucher_expires", columnList = "expires_at")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Voucher extends BaseEntity {

    // ==========================================
    // BASIC INFO
    // ==========================================

    @Column(nullable = false, unique = true, length = 20)
    private String code;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    // ==========================================
    // DISCOUNT
    // ==========================================

    @Column(name = "discount_type", nullable = false, length = 20)
    private String discountType; // PERCENTAGE, FIXED_AMOUNT

    @Column(nullable = false)
    private Double discount;

    @Column(name = "max_discount_amount")
    private Double maxDiscountAmount; // Giảm tối đa (cho percentage)

    @Column(name = "min_order_amount")
    private Double minOrderAmount; // Đơn hàng tối thiểu

    // ==========================================
    // QUANTITY
    // ==========================================

    @Column(name = "total_quantity")
    private Integer totalQuantity;

    @Column(name = "remaining_quantity")
    @Builder.Default
    private Integer remainingQuantity = 0;

    @Column(name = "max_per_user")
    @Builder.Default
    private Integer maxPerUser = 1; // Mỗi user sử dụng tối đa bao nhiêu lần

    // ==========================================
    // VALIDITY
    // ==========================================

    @Column(name = "valid_from")
    private LocalDateTime validFrom;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt;

    // ==========================================
    // STATUS
    // ==========================================

    @Column(name = "is_active")
    @Builder.Default
    private Boolean isActive = true;

    @Column(name = "is_public")
    @Builder.Default
    private Boolean isPublic = true; // Public voucher có thể search được

    @Column(name = "is_featured")
    @Builder.Default
    private Boolean isFeatured = false;

    // ==========================================
    // APPLICABILITY
    // ==========================================

    @Column(name = "applicable_types", length = 255)
    private String applicableTypes; // PACKAGE_PURCHASE, BOOST_PURCHASE, SUBSCRIPTION

    @ElementCollection
    @CollectionTable(name = "voucher_applicable_packages", joinColumns = @JoinColumn(name = "voucher_id"))
    @Column(name = "package_id")
    @Builder.Default
    private Set<Long> applicablePackageIds = new HashSet<>();

    // ==========================================
    // USAGE TRACKING
    // ==========================================

    @Column(name = "used_count")
    @Builder.Default
    private Integer usedCount = 0;

    // ==========================================
    // CREATOR
    // ==========================================

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private Boolean isAutoGenerated = false;

    // ==========================================
    // HELPER METHODS
    // ==========================================

    /**
     * Kiểm tra voucher có đang active không
     */
    public boolean isActive() {
        if (!Boolean.TRUE.equals(isActive)) {
            return false;
        }
        return isValidNow() && hasRemainingQuantity();
    }

    /**
     * Kiểm tra voucher có đang trong thời gian valid không
     */
    public boolean isValidNow() {
        LocalDateTime now = LocalDateTime.now();

        if (validFrom != null && now.isBefore(validFrom)) {
            return false;
        }

        if (expiresAt != null && now.isAfter(expiresAt)) {
            return false;
        }

        return true;
    }

    /**
     * Kiểm tra còn số lượng không
     */
    public boolean hasRemainingQuantity() {
        if (totalQuantity == null) {
            return true; // Unlimited
        }
        return remainingQuantity != null && remainingQuantity > 0;
    }

    /**
     * Kiểm tra voucher có phải loại percentage không
     */
    public boolean isPercentage() {
        return "PERCENTAGE".equals(discountType);
    }

    /**
     * Tính số tiền giảm
     */
    public Double calculateDiscount(Double orderAmount) {
        if (orderAmount == null || orderAmount < getMinOrderAmount()) {
            return 0.0;
        }

        Double discountAmount;
        if (isPercentage()) {
            discountAmount = orderAmount * discount / 100;
            if (maxDiscountAmount != null && discountAmount > maxDiscountAmount) {
                discountAmount = maxDiscountAmount;
            }
        } else {
            discountAmount = discount;
        }

        return Math.min(discountAmount, orderAmount);
    }

    /**
     * Sử dụng voucher
     */
    public boolean use() {
        if (!hasRemainingQuantity()) {
            return false;
        }
        usedCount = (usedCount == null ? 0 : usedCount) + 1;
        remainingQuantity = (remainingQuantity == null ? totalQuantity : remainingQuantity) - 1;
        return true;
    }

    /**
     * Kiểm tra có áp dụng được cho package không
     */
    public boolean isApplicableForPackage(Long packageId) {
        if (applicablePackageIds == null || applicablePackageIds.isEmpty()) {
            return true; // Áp dụng cho tất cả
        }
        return applicablePackageIds.contains(packageId);
    }

    /**
     * Kiểm tra có áp dụng được cho loại không
     */
    public boolean isApplicableForType(String type) {
        if (applicableTypes == null || applicableTypes.isBlank()) {
            return true;
        }
        return applicableTypes.contains(type);
    }

    /**
     * Tạo mã voucher ngẫu nhiên
     */
    public static String generateCode() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder code = new StringBuilder();
        for (int i = 0; i < 8; i++) {
            code.append(chars.charAt((int) (Math.random() * chars.length())));
        }
        return code.toString();
    }
}
